### ISSUE TITLE
vng/push_pull branch throws errors on metlog client termination

### ISSUE THREAD

**Issue by crankycoder** [mozilla-services/metlog-py#30]
I'm not sure how to prevent these kinds of errors from showing up on process termination:

It looks like the Queue module loses it's Empty attribute during shutdown.

``` python
KeyboardInterrupt
Exception in thread Thread-8 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/usr/lib/python2.6/site-packages/metlog/senders/async_push/source.py", line 105, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/usr/lib/python2.6/site-packages/metlog/senders/async_push/source.py", line 105, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
Exception in thread Thread-4 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/usr/lib/python2.6/site-packages/metlog/senders/async_push/source.py", line 105, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
Exception in thread Thread-10 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/usr/lib/python2.6/site-packages/metlog/senders/async_push/source.py", line 105, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/usr/lib/python2.6/site-packages/metlog/senders/async_push/source.py", line 105, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
Exception in thread Thread-3 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/usr/lib/python2.6/site-packages/metlog/senders/async_push/source.py", line 105, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
Exception in thread Thread-5 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/usr/lib/python2.6/site-packages/metlog/senders/async_push/source.py", line 105, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
Exception in thread Thread-9 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/usr/lib/python2.6/site-packages/metlog/senders/async_push/source.py", line 105, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
Exception in thread Thread-7 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/usr/lib/python2.6/site-packages/metlog/senders/async_push/source.py", line 105, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
Exception in thread Thread-6 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/usr/lib/python2.6/site-packages/metlog/senders/async_push/source.py", line 105, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
make: *** [all] Error 1
```

**Comment by hannosch** [comment]
First I'd try to add an atexit handler to nicely end the "while True" loop.

Add a new method to the AsyncSender:

```
def stop(self):
    self.shutdown_connection = True
```

and then inside the run method, right before the "while True" add:

```
atexit.register(self.stop)
```

atexit is part of the standard library, so a module scope import of "import atexit" is fine.

Next you can try to change the imports, so you don't import Queue, but instead import Empty directly and use "Empty" instead of "Queue.Empty" inside the method. During system exit all garbage collection will kick in and set all entries in sys.modules to "None". So in your case the lookup of "Queue" points to "None" instead of the module object. If you keep a direct reference to the "Empty" class inside the method locals, that shouldn't be garbage collected while the method is still active.

As a reference here's what I did in qdo: https://github.com/mozilla-services/qdo/blob/master/qdo/worker.py#L147

**Comment by rfk** [comment]
Ugh, yeah, interpreter shutdown is a strange world where module attributes will be indiscriminately set to None to force garbage collection.

You can try to work around it by taking local copies of the exceptions into the class itself, like:

```
class AsyncSender(threading.Thread):

    QueueEmpty = Queue.Empty
    ZMQError = zmq.core.error.ZMQError

    def run(self):
        ...
        try:
            msg = self.queue.get(timeout=0.001)
            self.queue.task_done()
        except self.QueueEmpty, ignored: # NOQA
            pass
```

But it would be better to arrange for the thread to stop before the shutdown procedure starts.

**Comment by crankycoder** [comment]
Closing this as we've deprecated the 0mq plugin
